SELECT
PATIENT_SK,
PATIENT_ID,
FIRST_NAME,
LAST_NAME,
DATE_OF_BIRTH,
GENDER,
EMAIL,
PHONE,
ADDRESS,
INSURANCE_NUMBER,
INSURANCE_COMPANY,
MEDICAL_HISTORY,
EFFECTIVE_START_DATE,
EFFECTIVE_END_DATE,
IS_CURRENT,
SOURCE_SYSTEM,
CREATED_TIMESTAMP,
LOAD_TIMESTAMP
FROM {{ ref('dim_patient') }}
WHERE IS_CURRENT = FALSE