
WITH billing AS (
    SELECT *
    FROM {{ ref('fact_billing_history') }}
),
patient AS (
    SELECT PATIENT_SK,PATIENT_ID
    FROM {{ ref('dim_patient_current') }}
),
insurance AS (
    SELECT INSURANCE_SK,INSURANCE_NUMBER,INSURANCE_COMPANY,PLAN_NAME
    FROM {{ ref('dim_insurance_current') }}
),
date_dim AS (
    SELECT DATE_SK,FULL_DATE,YEAR,MONTH,MONTH_NAME,QUARTER
    FROM {{ ref('dim_date') }}
)
SELECT
    b.BILLING_ID,
    b.CLAIM_NUMBER,
    b.PATIENT_SK,
    p.PATIENT_ID,
    b.INSURANCE_SK,
    i.INSURANCE_NUMBER,
    i.INSURANCE_COMPANY,
    i.PLAN_NAME,
    b.DATE_SK,
    d.FULL_DATE AS BILLING_DATE,
    d.YEAR AS BILLING_YEAR,
    d.MONTH AS BILLING_MONTH,
    d.MONTH_NAME AS BILLING_MONTH_NAME,
    d.QUARTER AS BILLING_QUARTER,
    b.SERVICE_TYPE,
    b.AMOUNT AS CLAIM_AMOUNT,
    b.BILLING_STATUS,
    b.HAS_INSURANCE,
    CASE
        WHEN b.BILLING_STATUS = 'PAID' THEN b.AMOUNT
        ELSE 0
    END AS PAID_AMOUNT,
    CASE
        WHEN b.BILLING_STATUS IN ('DENIED','REJECTED') THEN b.AMOUNT
        ELSE 0
    END AS DENIED_AMOUNT,
    CASE
        WHEN b.BILLING_STATUS IN ('PENDING','SUBMITTED') THEN b.AMOUNT
        ELSE 0
    END AS PENDING_AMOUNT,
    CASE
        WHEN b.HAS_INSURANCE = TRUE THEN 'INSURED'
        ELSE 'SELF_PAY'
    END AS PAYMENT_TYPE,
    b.EFFECTIVE_START_DATE,
    b.EFFECTIVE_END_DATE,
    b.IS_CURRENT,
    b.SOURCE_SYSTEM,
    b.CREATED_TIMESTAMP,
    b.INGESTION_TIMESTAMP,
    CURRENT_TIMESTAMP() AS LOAD_TIMESTAMP
FROM billing b
LEFT JOIN patient p
ON b.PATIENT_SK = p.PATIENT_SK
LEFT JOIN insurance i
ON b.INSURANCE_SK = i.INSURANCE_SK
LEFT JOIN date_dim d
ON b.DATE_SK = d.DATE_SK