WITH patient AS (
SELECT *
FROM {{ ref('dim_patient_current') }}
),
insurance AS (
SELECT PATIENT_ID,INSURANCE_SK,INSURANCE_NUMBER,INSURANCE_COMPANY,PLAN_NAME,COVERAGE_AMOUNT,EFFECTIVE_DATE,EXPIRATION_DATE,STATUS
FROM {{ ref('dim_insurance_current') }}
),
visit_summary AS (
SELECT PATIENT_SK,COUNT(*) AS TOTAL_VISITS,MAX(APPOINTMENT_DATE) AS LAST_VISIT_DATE,MIN(APPOINTMENT_DATE) AS FIRST_VISIT_DATE
FROM {{ ref('fact_visit') }}
GROUP BY PATIENT_SK
),
diagnosis_summary AS (
SELECT PATIENT_SK,COUNT(*) AS TOTAL_DIAGNOSES,MAX(DIAGNOSIS_DATE) AS LAST_DIAGNOSIS_DATE
FROM {{ ref('fact_diagnosis') }}
GROUP BY PATIENT_SK
),
medication_summary AS (
SELECT PATIENT_SK,COUNT(*) AS TOTAL_MEDICATIONS
FROM {{ ref('fact_medication') }}
GROUP BY PATIENT_SK
),
lab_summary AS (
SELECT PATIENT_SK,COUNT(*) AS TOTAL_LAB_RESULTS,MAX(TEST_DATE) AS LAST_LAB_DATE
FROM {{ ref('fact_lab_result') }}
GROUP BY PATIENT_SK
),
billing_summary AS (
SELECT PATIENT_SK,COUNT(*) AS TOTAL_BILLING_RECORDS,SUM(AMOUNT) AS TOTAL_BILLED_AMOUNT,MAX(BILLING_DATE) AS LAST_BILLING_DATE
FROM {{ ref('fact_billing') }}
GROUP BY PATIENT_SK
)
SELECT
p.PATIENT_SK,
p.PATIENT_ID,
p.FIRST_NAME,
p.LAST_NAME,
p.DATE_OF_BIRTH,
p.GENDER,
p.EMAIL,
p.PHONE,
p.ADDRESS,
i.INSURANCE_SK,
i.INSURANCE_NUMBER,
i.INSURANCE_COMPANY,
i.PLAN_NAME,
i.COVERAGE_AMOUNT,
i.EFFECTIVE_DATE AS INSURANCE_EFFECTIVE_DATE,
i.EXPIRATION_DATE AS INSURANCE_EXPIRATION_DATE,
i.STATUS AS INSURANCE_STATUS,
CASE WHEN i.INSURANCE_SK IS NOT NULL THEN TRUE ELSE FALSE END AS HAS_INSURANCE,
COALESCE(v.TOTAL_VISITS,0) AS TOTAL_VISITS,
v.FIRST_VISIT_DATE,
v.LAST_VISIT_DATE,
COALESCE(d.TOTAL_DIAGNOSES,0) AS TOTAL_DIAGNOSES,
d.LAST_DIAGNOSIS_DATE,
COALESCE(m.TOTAL_MEDICATIONS,0) AS TOTAL_MEDICATIONS,
COALESCE(l.TOTAL_LAB_RESULTS,0) AS TOTAL_LAB_RESULTS,
l.LAST_LAB_DATE,
COALESCE(b.TOTAL_BILLING_RECORDS,0) AS TOTAL_BILLING_RECORDS,
COALESCE(b.TOTAL_BILLED_AMOUNT,0) AS TOTAL_BILLED_AMOUNT,
b.LAST_BILLING_DATE,
CURRENT_TIMESTAMP() AS LOAD_TIMESTAMP
FROM patient p
LEFT JOIN insurance i
ON TRIM(p.PATIENT_ID)=TRIM(i.PATIENT_ID)
LEFT JOIN visit_summary v
ON p.PATIENT_SK=v.PATIENT_SK
LEFT JOIN diagnosis_summary d
ON p.PATIENT_SK=d.PATIENT_SK
LEFT JOIN medication_summary m
ON p.PATIENT_SK=m.PATIENT_SK
LEFT JOIN lab_summary l
ON p.PATIENT_SK=l.PATIENT_SK
LEFT JOIN billing_summary b
ON p.PATIENT_SK=b.PATIENT_SK