WITH patient AS (
SELECT PATIENT_SK,PATIENT_ID,FIRST_NAME,LAST_NAME,DATE_OF_BIRTH,GENDER
FROM {{ ref('dim_patient_current') }}
),
visit_summary AS (
SELECT PATIENT_SK,COUNT(*) AS TOTAL_VISITS,MAX(APPOINTMENT_DATE) AS LAST_VISIT_DATE,MIN(APPOINTMENT_DATE) AS FIRST_VISIT_DATE
FROM {{ ref('fact_visit') }}
GROUP BY PATIENT_SK
),
diagnosis_summary AS (
SELECT PATIENT_SK,COUNT(*) AS TOTAL_DIAGNOSES,MAX(DIAGNOSIS_DATE) AS LAST_DIAGNOSIS_DATE
FROM {{ ref('fact_diagnosis') }}
GROUP BY PATIENT_SK
),
medication_summary AS (
SELECT PATIENT_SK,COUNT(*) AS TOTAL_MEDICATIONS,COUNT_IF(STATUS='ACTIVE') AS ACTIVE_MEDICATIONS
FROM {{ ref('fact_medication') }}
GROUP BY PATIENT_SK
),
lab_summary AS (
SELECT PATIENT_SK,COUNT(*) AS TOTAL_LAB_RESULTS,MAX(TEST_DATE) AS LAST_LAB_DATE,COUNT_IF(RESULT_STATUS='ABNORMAL') AS ABNORMAL_LAB_RESULTS
FROM {{ ref('fact_lab_result') }}
GROUP BY PATIENT_SK
)
SELECT
p.PATIENT_SK,
p.PATIENT_ID,
p.FIRST_NAME,
p.LAST_NAME,
p.DATE_OF_BIRTH,
p.GENDER,
COALESCE(v.TOTAL_VISITS,0) AS TOTAL_VISITS,
v.FIRST_VISIT_DATE,
v.LAST_VISIT_DATE,
COALESCE(d.TOTAL_DIAGNOSES,0) AS TOTAL_DIAGNOSES,
d.LAST_DIAGNOSIS_DATE,
COALESCE(m.TOTAL_MEDICATIONS,0) AS TOTAL_MEDICATIONS,
COALESCE(m.ACTIVE_MEDICATIONS,0) AS ACTIVE_MEDICATIONS,
COALESCE(l.TOTAL_LAB_RESULTS,0) AS TOTAL_LAB_RESULTS,
COALESCE(l.ABNORMAL_LAB_RESULTS,0) AS ABNORMAL_LAB_RESULTS,
l.LAST_LAB_DATE,
CURRENT_TIMESTAMP() AS LOAD_TIMESTAMP
FROM patient p
LEFT JOIN visit_summary v
ON p.PATIENT_SK=v.PATIENT_SK
LEFT JOIN diagnosis_summary d
ON p.PATIENT_SK=d.PATIENT_SK
LEFT JOIN medication_summary m
ON p.PATIENT_SK=m.PATIENT_SK
LEFT JOIN lab_summary l
ON p.PATIENT_SK=l.PATIENT_SK