WITH billing AS (
SELECT *
FROM {{ ref('fact_billing') }}
),
date_dim AS (
SELECT DATE_SK,FULL_DATE,YEAR,MONTH,MONTH_NAME,QUARTER
FROM {{ ref('dim_date') }}
)
SELECT
d.YEAR,
d.QUARTER,
d.MONTH,
d.MONTH_NAME,
COUNT(*) AS TOTAL_BILLING_RECORDS,
COUNT(DISTINCT b.BILLING_ID) AS TOTAL_CLAIMS,
COUNT(DISTINCT b.PATIENT_SK) AS UNIQUE_PATIENTS,
COUNT(DISTINCT b.INSURANCE_SK) AS UNIQUE_INSURANCE_PROVIDERS,
SUM(b.AMOUNT) AS TOTAL_REVENUE,
AVG(b.AMOUNT) AS AVERAGE_BILLING_AMOUNT,
SUM(CASE WHEN UPPER(b.BILLING_STATUS)='PAID' THEN b.AMOUNT ELSE 0 END) AS PAID_REVENUE,
SUM(CASE WHEN UPPER(b.BILLING_STATUS)='PENDING' THEN b.AMOUNT ELSE 0 END) AS PENDING_REVENUE,
SUM(CASE WHEN UPPER(b.BILLING_STATUS)='DENIED' THEN b.AMOUNT ELSE 0 END) AS DENIED_REVENUE,
COUNT_IF(UPPER(b.BILLING_STATUS)='PAID') AS PAID_CLAIMS,
COUNT_IF(UPPER(b.BILLING_STATUS)='PENDING') AS PENDING_CLAIMS,
COUNT_IF(UPPER(b.BILLING_STATUS)='DENIED') AS DENIED_CLAIMS,
CURRENT_TIMESTAMP() AS LOAD_TIMESTAMP
FROM billing b
LEFT JOIN date_dim d
ON b.DATE_SK=d.DATE_SK
GROUP BY d.YEAR,d.QUARTER,d.MONTH,d.MONTH_NAME