SELECT
    INSURANCE_ID,
    PLAN_NAME,
    COVERAGE_AMOUNT,
    STATUS,
    DBT_VALID_FROM,
    DBT_VALID_TO
FROM PATIENT_RECORD_DB.SNAPSHOTS.INSURANCE_SNAPSHOT
WHERE INSURANCE_ID='38a678f3-06eb-4308-ba9b-8807dbec0605'
ORDER BY DBT_VALID_FROM;